# Generated by Django 4.2.25 on 2026-03-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0009_entityattribute_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitypath",
            name="entity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to="entity.entity",
                verbose_name="Entity",
            ),
        ),
        migrations.AlterField(
            model_name="entityposition",
            name="entity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="entity.entity",
                verbose_name="Entity",
            ),
        ),
        migrations.CreateModel(
            name="EntityInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_states",
                    models.BooleanField(default=True, verbose_name="Share States?"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="entity.entity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entitypath",
            name="entity_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to="entity.entityinstance",
                verbose_name="Entity Instance",
            ),
        ),
        migrations.AddField(
            model_name="entityposition",
            name="entity_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="entity.entityinstance",
                verbose_name="Entity Instance",
            ),
        ),
    ]
