# Generated by Django 4.2.25 on 2026-03-09 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0009_entityattribute_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityCloneLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("share_states", models.BooleanField(default=True, verbose_name="Share States?")),
                ("created_datetime", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                (
                    "clone_entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clone_link",
                        to="entity.entity",
                        verbose_name="Clone Entity",
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clone_links_as_source",
                        to="entity.entity",
                        verbose_name="Source Entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Clone Link",
                "verbose_name_plural": "Entity Clone Links",
            },
        ),
        migrations.AddConstraint(
            model_name="entityclonelink",
            constraint=models.UniqueConstraint(
                fields=("source_entity", "clone_entity"),
                name="entity_clone_link_source_clone_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityclonelink",
            constraint=models.CheckConstraint(
                check=~models.Q(("source_entity", models.F("clone_entity"))),
                name="entity_clone_link_no_self_clone",
            ),
        ),
    ]
