# Generated by Django 4.2.25 on 2026-03-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0010_entityinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitystate",
            name="entity_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="entity.entityinstance",
                verbose_name="Entity Instance",
            ),
        ),
        migrations.AlterField(
            model_name="entitystate",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="entity.entity",
                verbose_name="Entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitypath",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entity_instance__isnull", False)),
                fields=("location", "entity_instance"),
                name="entity_path_location_entity_instance",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitypath",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("entity__isnull", False), ("entity_instance__isnull", True)
                    ),
                    models.Q(
                        ("entity__isnull", True), ("entity_instance__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="entity_path_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityposition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entity_instance__isnull", False)),
                fields=("location", "entity_instance"),
                name="entity_position_location_entity_instance",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityposition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("entity__isnull", False), ("entity_instance__isnull", True)
                    ),
                    models.Q(
                        ("entity__isnull", True), ("entity_instance__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="entity_position_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitystate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("entity__isnull", False), ("entity_instance__isnull", True)
                    ),
                    models.Q(
                        ("entity__isnull", True), ("entity_instance__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="entity_state_exactly_one_owner",
            ),
        ),
    ]
